### ISSUE TITLE
Import problem when try to run on commandline

### ISSUE THREAD

**Issue by harmomyshoes** [microsoft/fadtk#19]
After 
Install torch and fadtk

C:\Users\XX> python -m fadtk.test
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\XX\.conda\envs\CodecCrack\Lib\site-packages\fadtk\__init__.py", line 1, in <module>
    from .fad import *
  File "C:\Users\XX\.conda\envs\CodecCrack\Lib\site-packages\fadtk\fad.py", line 11, in <module>
    from scipy import sqrt as scisqrt
ImportError: cannot import name 'sqrt' from 'scipy' (C:\Users\XX\.conda\envs\CodecCrack\Lib\site-packages\scipy\__init__.py)

**Comment by hykilpikonna** [comment]
Which python version and scipy library version are you using? Please attach the output of `python -VVV` and `pip list`

Using Python 3.11.6 and Scipy 1.11.3, I did not have an issue importing sqrt from scipy:

![image](https://github.com/microsoft/fadtk/assets/22280294/37cb8521-f1f5-49a1-86e8-83ff123abe3c)

**Comment by harmomyshoes** [comment]
scipy  1.12.0, python version 3.11
will try that scipy version. thanks for the answer.

**Comment by harmomyshoes** [comment]
it works.thanks again
